# Generated by Django 5.2.17 on 2026-09-22 02:47

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import rms.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pgcrypto", reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('request_method', models.CharField(max_length=8)),
                ('request_path', models.CharField(max_length=512)),
                ('request_sha256', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_identity', models.CharField(max_length=128)),
                ('response_bytes', models.BinaryField()),
                ('response_sha256', models.GeneratedField(db_persist=True, expression=rms.models.Encode(rms.models.Digest(models.F('response_bytes'), models.Value('sha256')), models.Value('hex')), output_field=models.CharField(max_length=64))),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=128, unique=True)),
                ('synthetic', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('synthetic', True)), name='source_synthetic_true')],
            },
        ),
        migrations.CreateModel(
            name='SourceManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('through_version', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('version_count', models.PositiveIntegerField()),
                ('manifest_bytes', models.BinaryField()),
                ('byte_length', models.GeneratedField(db_persist=True, expression=rms.models.OctetLength(models.F('manifest_bytes')), output_field=models.IntegerField())),
                ('manifest_sha256', models.GeneratedField(db_persist=True, expression=rms.models.Encode(rms.models.Digest(models.F('manifest_bytes'), models.Value('sha256')), models.Value('hex')), output_field=models.CharField(max_length=64))),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifests', to='rms.source')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'through_version'), name='source_manifest_through_unique'), models.CheckConstraint(condition=models.Q(('through_version__gt', 0)), name='source_manifest_version_positive'), models.CheckConstraint(condition=models.Q(('schema_version', 1)), name='source_manifest_schema_one'), models.CheckConstraint(condition=models.Q(('version_count', models.F('through_version'))), name='source_manifest_count_matches')],
            },
        ),
        migrations.CreateModel(
            name='SourceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('corrects_version', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.BinaryField()),
                ('byte_length', models.GeneratedField(db_persist=True, expression=rms.models.OctetLength(models.F('content')), output_field=models.IntegerField())),
                ('content_sha256', models.GeneratedField(db_persist=True, expression=rms.models.Encode(rms.models.Digest(models.F('content'), models.Value('sha256')), models.Value('hex')), output_field=models.CharField(max_length=64))),
                ('synthetic', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.source')),
            ],
            options={
                'ordering': ['version'],
                'constraints': [models.UniqueConstraint(fields=('source', 'version'), name='source_version_unique'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='source_version_positive'), models.CheckConstraint(condition=models.Q(('synthetic', True)), name='source_version_synthetic_true'), models.CheckConstraint(condition=models.Q(models.Q(('corrects_version__isnull', True), ('version', 1)), models.Q(('version__gt', 1), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1)))), _connector='OR'), name='source_version_immediate_predecessor')],
            },
        ),
    ]
