# Generated by Django 5.2.17 on 2026-10-03 15:11

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import functools
import rms.hypothesis_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_source_idea_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('HYP',), **{}), editable=False, max_length=42, unique=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('synthetic', True)), name='hypothesis_synthetic')],
            },
        ),
        migrations.CreateModel(
            name='HypothesisVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1', editable=False, max_length=128)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('impact_status', models.CharField(default='unreviewed', editable=False, max_length=16)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('fields', models.JSONField(default=dict)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('HYPV',), **{}), editable=False, max_length=42, unique=True)),
                ('state', models.CharField(default='draft', editable=False, max_length=16)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.hypothesis')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('INV',), **{}), editable=False, max_length=42, unique=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('synthetic', True)), name='investigation_synthetic')],
            },
        ),
        migrations.CreateModel(
            name='InvestigationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1', editable=False, max_length=128)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('impact_status', models.CharField(default='unreviewed', editable=False, max_length=16)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('fields', models.JSONField(default=dict)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('INVV',), **{}), editable=False, max_length=42, unique=True)),
                ('state', models.CharField(default='proposed', editable=False, max_length=16)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.investigation')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriorResearchAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('PRA',), **{}), editable=False, max_length=42, unique=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('synthetic', True)), name='priorresearchassessment_synthetic')],
            },
        ),
        migrations.CreateModel(
            name='PriorResearchAssessmentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1', editable=False, max_length=128)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('impact_status', models.CharField(default='unreviewed', editable=False, max_length=16)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('fields', models.JSONField(default=dict)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('PRAV',), **{}), editable=False, max_length=42, unique=True)),
                ('state', models.CharField(default='recorded', editable=False, max_length=16)),
                ('link_count', models.PositiveSmallIntegerField(editable=False)),
                ('link_digest', models.CharField(editable=False, max_length=64)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.priorresearchassessment')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchAssociationIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('RAS',), **{}), editable=False, max_length=42, unique=True)),
                ('idea_version', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_identity', to='rms.ideaversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentExternalReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1', editable=False, max_length=128)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('impact_status', models.CharField(default='unreviewed', editable=False, max_length=16)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('fields', models.JSONField(default=dict)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('AERV',), **{}), editable=False, max_length=42, unique=True)),
                ('state', models.CharField(default='recorded', editable=False, max_length=16)),
                ('reference', models.CharField(max_length=4000)),
                ('position', models.PositiveSmallIntegerField(editable=False)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='rms.priorresearchassessmentversion')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_versions', to='rms.researchassociationidentity')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('RFAM',), **{}), editable=False, max_length=42, unique=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('synthetic', True)), name='researchfamily_synthetic')],
            },
        ),
        migrations.CreateModel(
            name='ResearchFamilyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1', editable=False, max_length=128)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('impact_status', models.CharField(default='unreviewed', editable=False, max_length=16)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('fields', models.JSONField(default=dict)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('RFAMV',), **{}), editable=False, max_length=42, unique=True)),
                ('state', models.CharField(default='recorded', editable=False, max_length=16)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.researchfamily')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1', editable=False, max_length=128)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('impact_status', models.CharField(default='unreviewed', editable=False, max_length=16)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('fields', models.JSONField(default=dict)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('RASV',), **{}), editable=False, max_length=42, unique=True)),
                ('state', models.CharField(default='effective', editable=False, max_length=16)),
                ('kind', models.CharField(max_length=32)),
                ('rationale', models.CharField(max_length=4000, null=True)),
                ('origin_type', models.CharField(editable=False, max_length=16, null=True)),
                ('position', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('assessment_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_associations', to='rms.priorresearchassessmentversion')),
                ('hypothesis_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_associations', to='rms.hypothesisversion')),
                ('idea_family_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hypothesis_bindings', to='rms.researchassociation')),
                ('idea_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_associations', to='rms.ideaversion')),
                ('investigation_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_associations', to='rms.investigationversion')),
                ('source_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_associations', to='rms.sourceversion')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.researchassociationidentity')),
                ('family_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_associations', to='rms.researchfamilyversion')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HypothesisCorrectionImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1', editable=False, max_length=128)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('impact_status', models.CharField(default='unreviewed', editable=False, max_length=16)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('fields', models.JSONField(default=dict)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('HCIV',), **{}), editable=False, max_length=42, unique=True)),
                ('state', models.CharField(default='review_needed', editable=False, max_length=16)),
                ('newer_idea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_hypothesis_impacts', to='rms.ideaversion')),
                ('newer_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_hypothesis_impacts', to='rms.sourceversion')),
                ('pinned_idea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinned_hypothesis_impacts', to='rms.ideaversion')),
                ('pinned_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinned_hypothesis_impacts', to='rms.sourceversion')),
                ('hypothesis_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_impacts', to='rms.hypothesisversion')),
                ('newer_investigation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_hypothesis_impacts', to='rms.investigationversion')),
                ('pinned_investigation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinned_hypothesis_impacts', to='rms.investigationversion')),
                ('newer_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_hypothesis_impacts', to='rms.priorresearchassessmentversion')),
                ('pinned_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinned_hypothesis_impacts', to='rms.priorresearchassessmentversion')),
                ('newer_association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_hypothesis_impacts', to='rms.researchassociation')),
                ('pinned_association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinned_hypothesis_impacts', to='rms.researchassociation')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_versions', to='rms.researchassociationidentity')),
                ('newer_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_hypothesis_impacts', to='rms.researchfamilyversion')),
                ('pinned_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinned_hypothesis_impacts', to='rms.researchfamilyversion')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='hypothesisversion',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='hypothesisversion_sequence'),
        ),
        migrations.AddConstraint(
            model_name='hypothesisversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='hypothesisversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='hypothesisversion',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1'), ('classification', 'synthetic'), ('schema_version', '1.0')), name='hypothesisversion_scope'),
        ),
        migrations.AddConstraint(
            model_name='hypothesisversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='hypothesisversion_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='hypothesisversion',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'draft')), name='hypothesis_draft'),
        ),
        migrations.AddConstraint(
            model_name='investigationversion',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='investigationversion_sequence'),
        ),
        migrations.AddConstraint(
            model_name='investigationversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='investigationversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='investigationversion',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1'), ('classification', 'synthetic'), ('schema_version', '1.0')), name='investigationversion_scope'),
        ),
        migrations.AddConstraint(
            model_name='investigationversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='investigationversion_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='investigationversion',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'proposed')), name='investigation_proposed'),
        ),
        migrations.AddConstraint(
            model_name='priorresearchassessmentversion',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='priorresearchassessmentversion_sequence'),
        ),
        migrations.AddConstraint(
            model_name='priorresearchassessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='priorresearchassessmentversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='priorresearchassessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1'), ('classification', 'synthetic'), ('schema_version', '1.0')), name='priorresearchassessmentversion_scope'),
        ),
        migrations.AddConstraint(
            model_name='priorresearchassessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='priorresearchassessmentversion_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='priorresearchassessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'recorded')), name='assessment_recorded'),
        ),
        migrations.AddConstraint(
            model_name='priorresearchassessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(link_count__lte=100, link_digest__regex=r'^[0-9a-f]{64}$') & ~models.Q(fields__has_key='record_links'), name='assessment_link_seal_shape'),
        ),
        migrations.AddConstraint(
            model_name='researchassociationidentity',
            constraint=models.CheckConstraint(condition=models.Q(('synthetic', True)), name='researchassociationidentity_synthetic'),
        ),
        migrations.AddConstraint(
            model_name='assessmentexternalreference',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='assessmentexternalreference_sequence'),
        ),
        migrations.AddConstraint(
            model_name='assessmentexternalreference',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='assessmentexternalreference_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentexternalreference',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1'), ('classification', 'synthetic'), ('schema_version', '1.0')), name='assessmentexternalreference_scope'),
        ),
        migrations.AddConstraint(
            model_name='assessmentexternalreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='assessmentexternalreference_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='researchfamilyversion',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='researchfamilyversion_sequence'),
        ),
        migrations.AddConstraint(
            model_name='researchfamilyversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='researchfamilyversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='researchfamilyversion',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1'), ('classification', 'synthetic'), ('schema_version', '1.0')), name='researchfamilyversion_scope'),
        ),
        migrations.AddConstraint(
            model_name='researchfamilyversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='researchfamilyversion_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='researchfamilyversion',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'recorded')), name='family_recorded'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='researchassociation_sequence'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='researchassociation_positive'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1'), ('classification', 'synthetic'), ('schema_version', '1.0')), name='researchassociation_scope'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='researchassociation_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'effective')), name='association_effective'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assessment_version__isnull', True), ('family_version__isnull', False), ('hypothesis_version__isnull', True), ('idea_family_version__isnull', True), ('idea_version__isnull', False), ('investigation_version__isnull', True), ('kind', 'IdeaFamily'), ('source_version__isnull', True)), models.Q(('assessment_version__isnull', True), ('family_version__isnull', False), ('hypothesis_version__isnull', True), ('idea_family_version__isnull', True), ('idea_version__isnull', True), ('investigation_version__isnull', False), ('kind', 'InvestigationFamily'), ('source_version__isnull', True)), models.Q(('assessment_version__isnull', False), ('family_version__isnull', True), ('hypothesis_version__isnull', True), ('idea_family_version__isnull', True), ('idea_version__isnull', True), ('investigation_version__isnull', False), ('kind', 'PriorResearchInvestigation'), ('source_version__isnull', True)), models.Q(('assessment_version__isnull', True), ('family_version__isnull', True), ('hypothesis_version__isnull', False), ('idea_family_version__isnull', True), ('idea_version__isnull', True), ('investigation_version__isnull', False), ('kind', 'HypothesisInvestigation'), ('source_version__isnull', True)), models.Q(('assessment_version__isnull', True), ('family_version__isnull', True), ('hypothesis_version__isnull', False), ('idea_family_version__isnull', False), ('idea_version__isnull', False), ('investigation_version__isnull', True), ('kind', 'IdeaHypothesis'), ('source_version__isnull', True)), models.Q(('assessment_version__isnull', False), ('family_version__isnull', True), ('hypothesis_version__isnull', True), ('idea_family_version__isnull', True), ('idea_version__isnull', False), ('investigation_version__isnull', True), ('kind', 'AssessmentRecord'), ('source_version__isnull', True)), models.Q(('assessment_version__isnull', False), ('family_version__isnull', True), ('hypothesis_version__isnull', True), ('idea_family_version__isnull', True), ('idea_version__isnull', True), ('investigation_version__isnull', True), ('kind', 'AssessmentRecord'), ('source_version__isnull', False)), models.Q(('assessment_version__isnull', False), ('family_version__isnull', False), ('hypothesis_version__isnull', True), ('idea_family_version__isnull', True), ('idea_version__isnull', True), ('investigation_version__isnull', True), ('kind', 'AssessmentRecord'), ('source_version__isnull', True)), models.Q(('assessment_version__isnull', False), ('family_version__isnull', True), ('hypothesis_version__isnull', True), ('idea_family_version__isnull', True), ('idea_version__isnull', True), ('investigation_version__isnull', False), ('kind', 'AssessmentRecord'), ('source_version__isnull', True)), _connector='OR'), name='association_endpoint_shape'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'IdeaHypothesis'), ('origin_type', 'direct'), ('rationale__isnull', False)), models.Q(models.Q(('kind', 'IdeaHypothesis'), _negated=True), ('origin_type__isnull', True)), _connector='OR'), name='association_direct_origin'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['IdeaHypothesis', 'HypothesisInvestigation'])), fields=('hypothesis_version', 'kind'), name='hypothesis_single_endpoints'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['InvestigationFamily', 'PriorResearchInvestigation'])), fields=('investigation_version', 'kind'), name='investigation_single_context'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='hypothesiscorrectionimpact_sequence'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='hypothesiscorrectionimpact_positive'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-140:contract:3982eccc-e180-4ac9-bc70-9c4e16aa47f1'), ('classification', 'synthetic'), ('schema_version', '1.0')), name='hypothesiscorrectionimpact_scope'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='hypothesiscorrectionimpact_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'review_needed')), name='impact_review_needed'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('newer_assessment__isnull', True), ('newer_association__isnull', True), ('newer_family__isnull', True), ('newer_idea__isnull', True), ('newer_investigation__isnull', True), ('newer_source__isnull', False), ('pinned_assessment__isnull', True), ('pinned_association__isnull', True), ('pinned_family__isnull', True), ('pinned_idea__isnull', True), ('pinned_investigation__isnull', True), ('pinned_source__isnull', False)), models.Q(('newer_assessment__isnull', True), ('newer_association__isnull', True), ('newer_family__isnull', True), ('newer_idea__isnull', False), ('newer_investigation__isnull', True), ('newer_source__isnull', True), ('pinned_assessment__isnull', True), ('pinned_association__isnull', True), ('pinned_family__isnull', True), ('pinned_idea__isnull', False), ('pinned_investigation__isnull', True), ('pinned_source__isnull', True)), models.Q(('newer_assessment__isnull', True), ('newer_association__isnull', True), ('newer_family__isnull', False), ('newer_idea__isnull', True), ('newer_investigation__isnull', True), ('newer_source__isnull', True), ('pinned_assessment__isnull', True), ('pinned_association__isnull', True), ('pinned_family__isnull', False), ('pinned_idea__isnull', True), ('pinned_investigation__isnull', True), ('pinned_source__isnull', True)), models.Q(('newer_assessment__isnull', True), ('newer_association__isnull', True), ('newer_family__isnull', True), ('newer_idea__isnull', True), ('newer_investigation__isnull', False), ('newer_source__isnull', True), ('pinned_assessment__isnull', True), ('pinned_association__isnull', True), ('pinned_family__isnull', True), ('pinned_idea__isnull', True), ('pinned_investigation__isnull', False), ('pinned_source__isnull', True)), models.Q(('newer_assessment__isnull', False), ('newer_association__isnull', True), ('newer_family__isnull', True), ('newer_idea__isnull', True), ('newer_investigation__isnull', True), ('newer_source__isnull', True), ('pinned_assessment__isnull', False), ('pinned_association__isnull', True), ('pinned_family__isnull', True), ('pinned_idea__isnull', True), ('pinned_investigation__isnull', True), ('pinned_source__isnull', True)), models.Q(('newer_assessment__isnull', True), ('newer_association__isnull', False), ('newer_family__isnull', True), ('newer_idea__isnull', True), ('newer_investigation__isnull', True), ('newer_source__isnull', True), ('pinned_assessment__isnull', True), ('pinned_association__isnull', False), ('pinned_family__isnull', True), ('pinned_idea__isnull', True), ('pinned_investigation__isnull', True), ('pinned_source__isnull', True)), _connector='OR'), name='impact_endpoint_pair'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.UniqueConstraint(fields=('hypothesis_version', 'newer_source'), name='impact_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.UniqueConstraint(fields=('hypothesis_version', 'newer_idea'), name='impact_idea_unique'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.UniqueConstraint(fields=('hypothesis_version', 'newer_family'), name='impact_family_unique'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.UniqueConstraint(fields=('hypothesis_version', 'newer_investigation'), name='impact_investigation_unique'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.UniqueConstraint(fields=('hypothesis_version', 'newer_assessment'), name='impact_assessment_unique'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.UniqueConstraint(fields=('hypothesis_version', 'newer_association'), name='impact_association_unique'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.CheckConstraint(condition=models.Q(fields={}), name='association_no_id_arrays'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.CheckConstraint(condition=models.Q(kind='AssessmentRecord', position__gt=0) | (~models.Q(kind='AssessmentRecord') & models.Q(position__isnull=True)), name='association_position_shape'),
        ),
        migrations.AddConstraint(
            model_name='researchassociation',
            constraint=models.UniqueConstraint(fields=['assessment_version', 'position'], condition=models.Q(kind='AssessmentRecord'), name='assessment_link_position'),
        ),
        migrations.AddConstraint(
            model_name='assessmentexternalreference',
            constraint=models.CheckConstraint(condition=models.Q(state='recorded', fields={}, position__gt=0), name='external_reference_shape'),
        ),
        migrations.AddConstraint(
            model_name='assessmentexternalreference',
            constraint=models.UniqueConstraint(fields=['assessment_version', 'position'], name='external_reference_position'),
        ),
        migrations.AddConstraint(
            model_name='hypothesiscorrectionimpact',
            constraint=models.CheckConstraint(condition=models.Q(fields={}), name='impact_no_id_arrays'),
        ),
    ]
