# Generated by Django 5.2.17 on 2026-10-03 23:36

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import functools
import rms.hypothesis_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0005_hypothesis_history_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('CRT',), **{}), editable=False, max_length=42, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('DREQ',), **{}), editable=False, max_length=42, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriterionProfileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-150:contract:dec62ed2-adab-4ab3-bbfd-8dffbcee897d', editable=False, max_length=128)),
                ('state', models.CharField(default='draft', editable=False, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('content_digest', models.CharField(editable=False, max_length=64)),
                ('fields', models.JSONField(default=dict)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('CRTV',), **{}), editable=False, max_length=42, unique=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.criterionprofile')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataRequirementVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-150:contract:dec62ed2-adab-4ab3-bbfd-8dffbcee897d', editable=False, max_length=128)),
                ('state', models.CharField(default='draft', editable=False, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('content_digest', models.CharField(editable=False, max_length=64)),
                ('fields', models.JSONField(default=dict)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('DREQV',), **{}), editable=False, max_length=42, unique=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.datarequirement')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('latest_version', models.PositiveIntegerField(default=0, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('TPL',), **{}), editable=False, max_length=42, unique=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('synthetic', True)), name='testplan_synthetic')],
            },
        ),
        migrations.AddField(
            model_name='datarequirement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms.testplan'),
        ),
        migrations.AddField(
            model_name='criterionprofile',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms.testplan'),
        ),
        migrations.CreateModel(
            name='TestPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0', editable=False, max_length=8)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-150:contract:dec62ed2-adab-4ab3-bbfd-8dffbcee897d', editable=False, max_length=128)),
                ('state', models.CharField(default='draft', editable=False, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('content_digest', models.CharField(editable=False, max_length=64)),
                ('fields', models.JSONField(default=dict)),
                ('corrects_version', models.PositiveIntegerField(editable=False, null=True)),
                ('correction_reason', models.CharField(max_length=4000, null=True)),
                ('changed_fields', models.JSONField(default=list, editable=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('TPLV',), **{}), editable=False, max_length=42, unique=True)),
                ('config_digest', models.CharField(editable=False, max_length=64)),
                ('configurations', models.JSONField(default=list, editable=False)),
                ('link_count', models.PositiveSmallIntegerField(editable=False)),
                ('link_digest', models.CharField(editable=False, max_length=64)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='rms.testplan')),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestPlanAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('TPAS',), **{}), editable=False, max_length=42, unique=True)),
                ('kind', models.CharField(max_length=32)),
                ('position', models.PositiveSmallIntegerField()),
                ('required', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('criterion_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_associations', to='rms.criterionprofileversion')),
                ('data_requirement_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_associations', to='rms.datarequirementversion')),
                ('hypothesis_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_plan_associations', to='rms.hypothesisversion')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associations', to='rms.testplanversion')),
            ],
            options={
                'ordering': ['kind', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=functools.partial(rms.hypothesis_models.identifier, *('DCHK',), **{}), editable=False, max_length=42, unique=True)),
                ('configuration_key', models.CharField(max_length=64)),
                ('configuration_digest', models.CharField(editable=False, max_length=64)),
                ('requirement_digest', models.CharField(editable=False, max_length=64)),
                ('fields', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(editable=False, max_length=150)),
                ('classification', models.CharField(default='synthetic', editable=False, max_length=16)),
                ('authority_reference', models.CharField(default='MAU-150:contract:dec62ed2-adab-4ab3-bbfd-8dffbcee897d', editable=False, max_length=128)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
                ('supersedes', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='rms.dataaccesscheck')),
                ('data_requirement_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_checks', to='rms.datarequirementversion')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_checks', to='rms.testplanversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='criterionprofileversion',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='criterionprofileversion_sequence'),
        ),
        migrations.AddConstraint(
            model_name='criterionprofileversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='criterionprofileversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='criterionprofileversion',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-150:contract:dec62ed2-adab-4ab3-bbfd-8dffbcee897d'), ('classification', 'synthetic'), ('schema_version', '1.0'), ('state', 'draft')), name='criterionprofileversion_scope'),
        ),
        migrations.AddConstraint(
            model_name='criterionprofileversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='criterionprofileversion_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='datarequirementversion',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='datarequirementversion_sequence'),
        ),
        migrations.AddConstraint(
            model_name='datarequirementversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='datarequirementversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='datarequirementversion',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-150:contract:dec62ed2-adab-4ab3-bbfd-8dffbcee897d'), ('classification', 'synthetic'), ('schema_version', '1.0'), ('state', 'draft')), name='datarequirementversion_scope'),
        ),
        migrations.AddConstraint(
            model_name='datarequirementversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='datarequirementversion_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='datarequirement',
            constraint=models.CheckConstraint(condition=models.Q(('synthetic', True)), name='datarequirement_synthetic'),
        ),
        migrations.AddConstraint(
            model_name='criterionprofile',
            constraint=models.CheckConstraint(condition=models.Q(('synthetic', True)), name='criterionprofile_synthetic'),
        ),
        migrations.AddConstraint(
            model_name='testplanversion',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='testplanversion_sequence'),
        ),
        migrations.AddConstraint(
            model_name='testplanversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='testplanversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='testplanversion',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-150:contract:dec62ed2-adab-4ab3-bbfd-8dffbcee897d'), ('classification', 'synthetic'), ('schema_version', '1.0'), ('state', 'draft')), name='testplanversion_scope'),
        ),
        migrations.AddConstraint(
            model_name='testplanversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason__isnull', True), ('corrects_version__isnull', True), ('version', 1)), models.Q(('correction_reason__isnull', False), ('corrects_version', django.db.models.expressions.CombinedExpression(models.F('version'), '-', models.Value(1))), ('version__gt', 1), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='testplanversion_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='testplanassociation',
            constraint=models.UniqueConstraint(fields=('plan_version', 'kind', 'position'), name='tp_edge_position'),
        ),
        migrations.AddConstraint(
            model_name='testplanassociation',
            constraint=models.UniqueConstraint(fields=('plan_version', 'criterion_version'), name='tp_unique_criterion'),
        ),
        migrations.AddConstraint(
            model_name='testplanassociation',
            constraint=models.UniqueConstraint(fields=('plan_version', 'data_requirement_version'), name='tp_unique_data'),
        ),
        migrations.AddConstraint(
            model_name='testplanassociation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('criterion_version__isnull', True), ('data_requirement_version__isnull', True), ('hypothesis_version__isnull', False), ('kind', 'HypothesisPlan'), ('position', 0), ('required', True)), models.Q(('criterion_version__isnull', False), ('data_requirement_version__isnull', True), ('hypothesis_version__isnull', True), ('kind', 'PlanCriterion'), ('position__gt', 0)), models.Q(('criterion_version__isnull', True), ('data_requirement_version__isnull', False), ('hypothesis_version__isnull', True), ('kind', 'PlanDataRequirement'), ('position__gt', 0)), _connector='OR'), name='tp_edge_shape'),
        ),
        migrations.AddConstraint(
            model_name='dataaccesscheck',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', True)), fields=('plan_version', 'data_requirement_version', 'configuration_key'), name='tp_check_one_root'),
        ),
        migrations.AddConstraint(
            model_name='dataaccesscheck',
            constraint=models.CheckConstraint(condition=models.Q(('authority_reference', 'MAU-150:contract:dec62ed2-adab-4ab3-bbfd-8dffbcee897d'), ('classification', 'synthetic')), name='tp_check_scope'),
        ),
        migrations.AddConstraint(
            model_name='dataaccesscheck',
            constraint=models.CheckConstraint(condition=models.Q(('fields__outcome__in', ['passed', 'failed', 'inconclusive']), ('fields__sanitized_evidence_confirmed', True)), name='tp_check_report_shape'),
        ),
    ]
